sudo: true #we need this to run job on virtual machine not inside docker container
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r dashboard/requirements.txt

script:
  - tests/run_tests
  - bin/lint

deploy:
  - provider: script
    script: bash bin/deploy_to_dockerhub dev
    on:
      tags: false
      branch: master
  - provider: script
    script: bash bin/deploy_to_dockerhub "$TRAVIS_TAG" latest
    on:
      tags: true
      branch: master

